version: "3.4"
services:
  consumer-js:
    restart: unless-stopped
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: consumer_js
    network_mode: host
