version: '2'
services:
  acquirer_1:
    container_name: acquirer-1
    build:
      context: .
      dockerfile: Dockerfile.acquirer
      
  acquirer_2:
    container_name: acquirer-2
    build:
      context: .
      dockerfile: Dockerfile.acquirer
      
  database:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile.database
      
  processed-payments-handler:
    container_name: processed-payments-handler
    build:
      context: .
      dockerfile: Dockerfile.processed-payments-handler
      
  store:
    container_name: store
    build:
      context: .
      dockerfile: Dockerfile.store
    ports:
      - "3000:3000"
      
networks:
  default:
    external: true
    name: kafka